MainPage:

<MainPage>:
    StackLayout:
        size_hint: None, None
        size: '500dp', '200dp'
        cols: 3
        Button:
            text:'Arm'
        Button:
            text:'Disarm'
        Button:
            text:'Guided'
        Button:
            text:'Takeoff'
        Button:
            text:'Set velocity'
        Button:
            text:'Transit 1-2-3'
        Button:
            text:'Transit 3-2-1'
    Label: 
        text: 'Hi'
        pos: '400dp', '400dp'
